stages:
  - build
  - deploy
  - release
  - destroy

cache:
  key: ${CI_PROJECT_NAME}
  paths:
    - node_modules/

build:
  stage: build
  image: "registry.gitlab.com/gitlab-org/cluster-integration/auto-build-image:latest"
  variables:
    DOCKER_TLS_CERTDIR: ""
    GC_REGISTRY_IMAGE: asia.gcr.io/$GCLOUD_PROJECT_ID/$CI_PROJECT_NAME
    ENV_VARIABLE: ${CI_COMMIT_BRANCH}_env
  services:
    - docker:20-dind
  before_script:
    - docker system prune -af
    - docker login -u _json_key -p "$(cat $GCLOUD_SERVICE_KEY)" https://asia.gcr.io
    - cat ${!ENV_VARIABLE} > .env
  script:
    - |
      if [[ -z "$CI_COMMIT_TAG" ]]; then
        export CI_APPLICATION_REPOSITORY=${CI_APPLICATION_REPOSITORY:-$GC_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG}
        export CI_APPLICATION_TAG=${CI_APPLICATION_TAG:-$CI_COMMIT_SHA}
      else
        cat ${master_env} > .env
        export CI_APPLICATION_REPOSITORY=${CI_APPLICATION_REPOSITORY:-$GC_REGISTRY_IMAGE}
        export CI_APPLICATION_TAG=${CI_APPLICATION_TAG:-$CI_COMMIT_TAG}
      fi
    - /build/build.sh
  rules:
    - if: "$CI_COMMIT_TAG || $CI_COMMIT_BRANCH && $CI_PIPELINE_SOURCE != 'schedule'"


staging:
  image: "registry.gitlab.com/gitlab-org/cluster-integration/auto-deploy-image:v2.0.1"
  variables:
    GC_REGISTRY_IMAGE: asia.gcr.io/$GCLOUD_PROJECT_ID/$CI_PROJECT_NAME
    KUBE_NAMESPACE: ${CI_PROJECT_NAME}-staging
  stage: deploy
  before_script:
    - apk add -u gettext
    - export CI_TLS_HOST=staging-loan-api.kooperasi.com binary_remote_addr='$binary_remote_addr' ssl_server_name='$ssl_server_name' fastcgi_script_name='$fastcgi_script_name' uri='$uri' query_string='$query_string' document_root='$document_root' server_name='$server_name' scheme='$scheme' request_method='$request_method' host='$host' proxy_protocol_addr='$proxy_protocol_addr' skip_cache='$skip_cache' http_cookie='$http_cookie' http_authorization='$http_authorization' upstream_cache_status='$upstream_cache_status' http_pragma='$http_pragma' request_uri='$request_uri'
    - export CI_APPLICATION_REPOSITORY=${CI_APPLICATION_REPOSITORY:-$GC_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG}:${CI_COMMIT_SHA}
    - export CI_REPLICAS=1
    - export LIMIT_CPU=500m
    - export LIMIT_MEMORY=1Gi
    - export MAX_REPLICAS=1
  script:
    - kubectl config get-contexts
  - kubectl config use-context ipaymu/ipaymu-core:sandbox
    - kubectl cluster-info
    - kubectl create ns $KUBE_NAMESPACE --dry-run -o yaml | kubectl apply -f -
    - kubectl version
    - kubectl api-versions | grep autoscaling
    - envsubst < k8s/template-gke.yaml | kubectl apply -f -
    - kubectl patch deployment ${CI_ENVIRONMENT_SLUG} -n $KUBE_NAMESPACE -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"$(date +%s)\"}}}}}"
    - kubectl -n $KUBE_NAMESPACE rollout status deploy/${CI_ENVIRONMENT_SLUG}
    - kubectl get all,ing -n $KUBE_NAMESPACE
  environment:
    name: staging
    url: https://${CI_TLS_HOST}
  rules:
    - if: $CI_PIPELINE_SOURCE != "schedule" && $CI_COMMIT_BRANCH == "staging"


destroy-staging:
  image: "registry.gitlab.com/gitlab-org/cluster-integration/auto-deploy-image:v2.0.1"
  variables:
    GC_REGISTRY_IMAGE: asia.gcr.io/$GCP_PROJECT_ID/$CI_PROJECT_NAME
    KUBE_NAMESPACE: ${CI_PROJECT_NAME}-staging
  stage: destroy
  before_script:
    - apk add -u gettext
    - export CI_TLS_HOST=$CI_COMMIT_BRANCH.ipaymu.link binary_remote_addr='$binary_remote_addr' ssl_server_name='$ssl_server_name' fastcgi_script_name='$fastcgi_script_name' uri='$uri' query_string='$query_string' document_root='$document_root' server_name='$server_name' scheme='$scheme' request_method='$request_method' host='$host' proxy_protocol_addr='$proxy_protocol_addr' skip_cache='$skip_cache' http_cookie='$http_cookie' http_authorization='$http_authorization' cookie_laravel_session='$cookie_laravel_session' upstream_cache_status='$upstream_cache_status' http_pragma='$http_pragma' request_uri='$request_uri'
    - export CI_APPLICATION_REPOSITORY=${CI_APPLICATION_REPOSITORY:-$GC_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG}:${CI_COMMIT_SHA}
    - export CI_REPLICAS=1
  script:
    - kubectl config get-contexts
    - kubectl config use-context ipaymu/ipaymu-core:sandbox
    - kubectl cluster-info
    - kubectl version
    - |
      set -e  # Exit on error
      # Check if namespace exists
      if ! kubectl get ns "${KUBE_NAMESPACE}" &>/dev/null; then
        echo "Namespace '${KUBE_NAMESPACE}' does not exist. Exiting..."
        exit 0  # Not a failure if the namespace doesn't exist
      fi

      # Check if there are deployments in the namespace
      deply=$(kubectl get deploy -n "${KUBE_NAMESPACE}" -o jsonpath='{.items[0].metadata.name}' 2>/dev/null || true)
      if [[ -n "$deply" ]]; then
        echo "Found deployment '$deply'. Deleting resources..."
        envsubst < k8s/template-gke.yaml | kubectl delete -f -
        # Delete namespace if it exists
        kubectl create ns $KUBE_NAMESPACE --dry-run -o yaml | kubectl delete -f - || echo "Namespace does not exist or cannot be deleted."
      else
        echo "No deployments found in namespace '${KUBE_NAMESPACE}'. Exiting..."
        exit 0  # No error; just no deployments to delete
      fi

  environment:
    name: $CI_COMMIT_BRANCH
    action: stop
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule" && $CI_COMMIT_BRANCH == "staging"


production:
  image: "registry.gitlab.com/gitlab-org/cluster-integration/auto-deploy-image:v2.0.1"
  variables:
    GC_REGISTRY_IMAGE: asia.gcr.io/$GCLOUD_PROJECT_ID/$CI_PROJECT_NAME
    KUBE_NAMESPACE: ${CI_PROJECT_NAME}-production
  stage: release
  before_script:
    - apk add -u gettext
    - export CI_TLS_HOST=ipaymu.link binary_remote_addr='$binary_remote_addr' ssl_server_name='$ssl_server_name' fastcgi_script_name='$fastcgi_script_name' uri='$uri' query_string='$query_string' document_root='$document_root' server_name='$server_name' scheme='$scheme' request_method='$request_method' host='$host' proxy_protocol_addr='$proxy_protocol_addr' skip_cache='$skip_cache' http_cookie='$http_cookie' http_authorization='$http_authorization' upstream_cache_status='$upstream_cache_status' http_pragma='$http_pragma' request_uri='$request_uri'
    - export CI_APPLICATION_REPOSITORY=${CI_APPLICATION_REPOSITORY:-$GC_REGISTRY_IMAGE}:${CI_COMMIT_TAG}
    - export CI_REPLICAS=1
    - export LIMIT_CPU=1
    - export LIMIT_MEMORY=1Gi
    - export MAX_REPLICAS=2
  script:
    - kubectl config get-contexts
    - kubectl config use-context ipaymu/ipaymu-core:sandbox
    - kubectl cluster-info
    - kubectl create ns $KUBE_NAMESPACE --dry-run -o yaml | kubectl apply -f -
    - kubectl version
    - kubectl api-versions | grep autoscaling
    - envsubst < k8s/template-gke.yaml | kubectl apply -f -
    - kubectl patch deployment ${CI_ENVIRONMENT_SLUG} -n $KUBE_NAMESPACE -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"$(date +%s)\"}}}}}"
    - kubectl -n $KUBE_NAMESPACE rollout status deploy/${CI_ENVIRONMENT_SLUG}
    - kubectl get all,ing -n $KUBE_NAMESPACE
  environment:
    name: production
    url: https://${CI_TLS_HOST}
  only:
    - tags
  when: manual
